# Generated by Django 4.2.5 on 2023-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='applicable_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
