# Generated by Django 4.2.5 on 2023-09-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_exchangerate_applicable_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedweather',
            old_name='descritpion',
            new_name='description',
        ),
    ]
